### ISSUE TITLE
PyArrow does not support Python 3.9

### ISSUE THREAD

**Issue by urbandub01** [okld/streamlit-pandas-profiling#20]
Hi, I like what you made here, it's super handy and wanted to collaborate more. I was publishing (via heroku) this app I made with streamlit pandas profiling but I am getting this error when trying to run streamlit pandas profiling:

StreamlitAPIException: To use Custom Components in Streamlit, you need to install PyArrow. Unfortunately, PyArrow does not yet support Python 3.9.

You can either switch to Python 3.8 with an environment manager like PyEnv, or stay on 3.9 by installing Streamlit with conda:

conda install -c conda-forge streamlit

I guess it's because of PyArrow or do you have an idea?

Hope you can check it out thanks.

**Comment by okld** [comment]
Hello @urbandub01, glad you find the component useful!

That pyarrow issue is related to streamlit directly rather than this component. There are two open issues btw: https://github.com/streamlit/streamlit/issues/2668 and https://github.com/streamlit/streamlit/issues/3370.

Could you try to add pyarrow to your requirements.txt? If this doesn't help and you still have an error, try to install streamlit with [conda on heroku](https://elements.heroku.com/buildpacks/conda/conda-buildpack), or switch to python 3.8 if your app supports it.
